### ISSUE TITLE
Dimensions of polaroid image?

### ISSUE THREAD

**Issue by Endogen** [getgrav/grav-plugin-shortcode-ui#12]
I like the `ui-polaroid` shortcode but i don't know which dimensions the picture needs to have in order to fill the frame perfectly.

**Comment by Endogen** [comment]
EDIT: Well, that was kind of a stupid question... Took a look at the CSS and found it out: 280x280

**Comment by rhukster** [comment]
It actually does adapt to pretty much any photo as long as the image is larger than 280x280.  Square images are going to give you the best results as you will have cropped them manually. However, it will simply center non-square images.

I used this shortcode in a custom project, and also had to switch to a smaller size for a certain media query. Here's the SCSS for that to give you an idea of what you would need to tweak in order to adjust the size if you required:

```
@include breakpoint(large-desktop-only) {
    .polaroid-wrapper {
        .polaroid {
            width: 200px;
            height: 240px;

            p {
                font-size: 15px;
                padding: 5px 10px;
            }
        }

        .polaroid-img {
            top: 6px;
            left: 5px;
            width: 188px;
            height: 188px;
        }


    }
}
```

**Comment by Endogen** [comment]
Thanks. I had a picture with 640x436 and got an empty area on the bottom. In my case it was ok to crop the image.
